### ISSUE TITLE
Enviorment and Urls wrong in postman examples

### ISSUE THREAD

**Issue by SevKohler** [ehrbase/documentation#6]
Urls contain often legacy url codes ({{api_uri_legacy}}) which dont work.
Often url parameters are missing see Create Ventilation Example:
{{api_uri}}/template 
should be
{{api_uri}}/definition/template/adl1.4 (i guess at least thats working for me)

**Comment by axelsiebert** [comment]
Hi @SevKohler,

I replaced the collection and environment with my latest status. You should now be able to use also the definition endpoint without the undefined variable which was a relict of times the definition endpoint has not been migrated from etherCIS project to our new implementation.
